program: ThompsonElias08.o getdouble.o
	gcc ThompsonElias08.o getdouble.o -o program

inputdouble.o: ThompsonElias08.c getdouble.h
	gcc -c ThompsonElias08.c 

getdouble.o: getdouble.c getdouble.h
	gcc -c getdouble.c
