program: ThompsonElias10.o getdouble.o
	gcc ThompsonElias10.o getdouble.o -o program

inputdouble.o: ThompsonElias10.c getdouble.h
	gcc -c ThompsonElias10.c 

getdouble.o: getdouble.c getdouble.h
	gcc -c getdouble.c
